-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 14:54:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hackathon2_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hackathon2_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hackathon2_db` DEFAULT CHARACTER SET utf8 ;
USE `Hackathon2_db` ;

-- -----------------------------------------------------
-- Table `Hackathon2_db`.`agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`agence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NOT NULL,
  `coordinates` VARCHAR(500) NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `Hackathon2_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`user` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(200) NOT NULL,
  `lastname` VARCHAR(200) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(3000) NOT NULL,
  `city` VARCHAR(100) NULL,
  `skill` VARCHAR(1000) NULL,
  `type` VARCHAR(200) NULL,
  `agence_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `agence_Id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_agence_idx` (`agence_Id` ASC) VISIBLE,
  CONSTRAINT `fk_user_agence`
    FOREIGN KEY (`agence_Id`)
    REFERENCES `Hackathon2_db`.`agence` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Hackathon2_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`project` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `used_tools` VARCHAR(1000) NULL,
  `progress_status` VARCHAR(500) NULL,
  `description` VARCHAR(3000) NULL,
  `thematic` VARCHAR(500) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Hackathon2_db`.`projet_has_agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`projet_has_agence` (
  `projet_Id` INT NOT NULL,
  `agence_Id` INT NOT NULL,
  PRIMARY KEY (`projet_Id`, `agence_Id`),
  INDEX `fk_projet_has_agence_agence1_idx` (`agence_Id` ASC) VISIBLE,
  INDEX `fk_projet_has_agence_projet1_idx` (`projet_Id` ASC) VISIBLE,
  CONSTRAINT `fk_projet_has_agence_projet1`
    FOREIGN KEY (`projet_Id`)
    REFERENCES `Hackathon2_db`.`project` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_has_agence_agence1`
    FOREIGN KEY (`agence_Id`)
    REFERENCES `Hackathon2_db`.`agence` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Hackathon2_db`.`user_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`user_has_project` (
  `user_Id` INT NOT NULL,
  `project_Id` INT NOT NULL,
  `role` VARCHAR(100) NULL,
  PRIMARY KEY (`user_Id`, `project_Id`),
  INDEX `fk_user_has_projet_projet1_idx` (`project_Id` ASC) VISIBLE,
  INDEX `fk_user_has_projet_user1_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_projet_user1`
    FOREIGN KEY (`user_Id`)
    REFERENCES `Hackathon2_db`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_projet_projet1`
    FOREIGN KEY (`project_Id`)
    REFERENCES `Hackathon2_db`.`project` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Hackathon2_db`.`user_liked_project`
-- -----------------------------------------------------



CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`user_liked_project` (
  `user_Id` INT NOT NULL,
  `project_Id` INT NOT NULL,
  PRIMARY KEY (`user_Id`, `project_Id`),
  INDEX `fk_user_liked_projet_projet1_idx` (`project_Id` ASC) VISIBLE,
  INDEX `fk_user_liked_projet_user1_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_user_liked_projet_user1`
    FOREIGN KEY (`user_Id`)
    REFERENCES `Hackathon2_db`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_liked_projet_projet1`
    FOREIGN KEY (`project_Id`)
    REFERENCES `Hackathon2_db`.`project` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);







-- -----------------------------------------------------
-- Table `Hackathon2_db`.`new`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hackathon2_db`.`new` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `contents` VARCHAR(3000) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `project_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `project_Id`),
  INDEX `fk_new_project1_idx` (`project_Id` ASC) VISIBLE,
  CONSTRAINT `fk_new_project1`
    FOREIGN KEY (`project_Id`)
    REFERENCES `Hackathon2_db`.`project` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ajout de données misssions dans la table
INSERT INTO `` (`Id`,`name`,`used_tools`,`progress_status`,`description`,`thematic`) VALUES (1,'The Idea Project','javascript','pending','This project is all about creating an awsome way to make people collaborate on amzing projects','ideas managemnt');
INSERT INTO `` (`Id`,`name`,`used_tools`,`progress_status`,`description`,`thematic`) VALUES (2,'Solar roof creation','PV panels + electricity manager','finished','The idea is to create solar panels to be installed on the roof of each agency to generate our own electricit while managing storage and production of elctricity with our own algorithm  for enhanced efficiency and reduced carbon impact','renewable energy');
INSERT INTO `` (`Id`,`name`,`used_tools`,`progress_status`,`description`,`thematic`) VALUES (3,'Light automation','Homebridge and raspberry pi','pending','Inefficient usage of lighting is responsible for ectricity overconsumption hence the idea to automate light extinction through the use of homebridge and a raspberry Pi','home automation');


-- ajout d'utilisateur pour peupler la table user
INSERT INTO `` (`Id`,`firstname`,`lastname`,`email`,`password`,`city`,`skill`,`type`,`agence_Id`) VALUES (1,'Basile','Roger','nantua@marcos.com','12345','Nirave','Project Management','developer',1);
INSERT INTO `` (`Id`,`firstname`,`lastname`,`email`,`password`,`city`,`skill`,`type`,`agence_Id`) VALUES (3,'Elise','Nimare','elise.nimare@lycos.net','54321','Buis-Les-baronnies','Data Scientist','developer',2);
